services:
  telegram-bot:
    container_name: telegram_bot
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "bot.js"]
